{ mkDerivation, base, bytestring, containers, glib, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.18.4";
  sha256 = "05lfpbnsa52b9af080dmvw87dwlxcbhf9hs30sgx0s2nnv99pys5";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = stdenv.lib.licenses.lgpl21;
}